services:

    semapps_bundle.file_uploader:
        class: VirtualAssembly\semappsBundle\Services\FileUploader
        arguments: ['%picture_directory%','%carto.domain%',]

    semapps_bundle.encryption:
        class: VirtualAssembly\semappsBundle\Services\Encryption
        arguments: ['%secret%']

    semapps_bundle.sparql_repository:
        class: VirtualAssembly\semappsBundle\Services\SparqlRepository
        arguments: ['@semantic_forms.client',"@semapps_bundle.conf_manager","@security.token_storage"]

    semapps_bundle.webservice_tools:
        class: VirtualAssembly\semappsBundle\Services\WebserviceTools
        arguments: ['@doctrine.orm.entity_manager','@security.token_storage','@security.authorization_checker','@semapps_bundle.conf_manager','@semantic_forms.client','@semapps_bundle.webservice_cache','@Knp\Bundle\MarkdownBundle\MarkdownParserInterface','@semapps_bundle.sparql_repository']

    semapps_bundle.context_manager:
        class: VirtualAssembly\semappsBundle\Services\ContextManager
        arguments: ['%kernel.cache_dir%','@semapps_bundle.sparql_repository','@doctrine.orm.entity_manager']

    semapps_bundle.conf_manager:
        class: VirtualAssembly\semappsBundle\Services\ConfManager
        arguments: ['@service_container','%typeToName%','%graphToName%']

    semapps_bundle.import_manager:
        class: VirtualAssembly\semappsBundle\Services\ImportManager
        arguments: ['@semantic_forms.client','@semapps_bundle.sparql_repository']
    semapps_bundle.invite_manager:
        class: VirtualAssembly\semappsBundle\Services\InviteManager
        arguments: ['%kernel.cache_dir%','@fos_user.util.token_generator']
    semapps_bundle.webservice_cache:
        class: VirtualAssembly\semappsBundle\Services\WebserviceCache
        arguments: ['%kernel.cache_dir%']
#
#    semappsBundle.voter:
#        class: VirtualAssembly\semappsBundle\Voters\ExampleVoter
#        arguments: ['@semapps_bundle.sparql_repository','@semantic_forms.client']
#        tags:
#          - { name: security.voter }
#        # small performance boost
#        public: false